### ISSUE TITLE
[Maps app] Upgrade OpenLayers

### ISSUE THREAD

**Issue by dsigdosystem** [ove/ove-apps#1]
<a href="https://github.com/senakafdo"><img src="https://avatars3.githubusercontent.com/u/3415383?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [senakafdo](https://github.com/senakafdo)**
_Sunday Sep 23, 2018 at 10:30 GMT_
_Originally opened as https://github.com/dsi-icl/ove/issues/45_

----

OL 3.5.0 is deprecated, upgrade maps app to use a newer version. We are also not using Cesium, though we are including it as a dependency.

**Comment by dsigdosystem** [comment]
<a href="https://github.com/senakafdo"><img src="https://avatars3.githubusercontent.com/u/3415383?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [senakafdo](https://github.com/senakafdo)**
_Monday Sep 24, 2018 at 18:16 GMT_

----

This also improves the build speeds of the images app, which is a side effect of babel not parsing all of the embedded JS scripts from OL.

**Comment by senakafdo** [comment]
We have opted to use OL 3.15.1 from npm, so some of the issues reported here no longer exists. We still need to upgrade to a newer version. Cesium is no longer referenced in the code.

**Comment by senakafdo** [comment]
#56 will be fixed when this issue is resolved.
