### ISSUE TITLE
Maps app broken in production as MapQuest layers do not work

### ISSUE THREAD

**Issue by jamesscottbrown** [ove/ove-apps#100]
Commit c3cdafefde3f upgraded OpenLayers from  `3.15.1` to`5.3.0`.

However, whilst OpenLayers 3 has an [ol.source.MapQuest](https://geoadmin.github.io/ol3/apidoc/ol.source.MapQuest.html) layer source, [OpenLayers 5 does not](https://openlayers.org/en/latest/apidoc/module-ol_layer_Layer.html).

This means that the LondonMaps and RunKeepers demos do not work at all, and simply display a grey screen.

They throw an uncaught `TypeError` on [this line](https://github.com/ove/ove-apps/blob/a9303df8a872bc17ca8d7772665c488ecf367e91/packages/ove-app-maps/src/client/libraries/openlayers.js#L59), when they reach the source for which `e.source.type.substring('ol.source.'.length)` is `"MapQuest"`, as `window.ol.source["MapQuest"]` is not a constructor.

**Comment by senakafdo** [comment]
MapQuest layers are not included in any Map Layer configuration by default. This is **not a bug**

**Comment by jamesscottbrown** [comment]
The maps configuration was apparently changed in https://github.com/dsi-icl/gdo-dsivisrepo/pull/35/, but this was not deployed.

**Comment by senakafdo** [comment]
It is deployed, as explained offline, but a script responsible for reloading content was not working properly. I'm happy to provide any further details to anyone else who were not around when I explained this.
