### ISSUE TITLE
[Images App] Image is not loaded until controller is opened

### ISSUE THREAD

**Issue by jamesscottbrown** [ove/ove-apps#111]
When a section running the Images App is created, the specified image is not loaded until the corresponding controller page is opened with a web browser.

This is extremely inconvenient if a large number of image sections have been created.

This is contrary to the behaviour of other apps (e.g. the HTML App), and also to what [the documentation suggests](An image can be loaded using the OVE APIs) ("An image can be loaded using the OVE APIs").

**Comment by senakafdo** [comment]
@jamesscottbrown, for the maps and images apps, there are two formats of providing state:
1. The minimum state information required by the controller
2. The full state information (inclusive of viewport details) required by the viewers

If you provide a state configuration inclusive of full viewport details, the viewers can load the state without the presence of a controller. However, the viewport information would be space/section geometry dependent and there is some math that is used in the controller to compute it. Therefore, it would not perhaps be straightforward to explain to someone in our documentation as to how they can generate it themselves.

To validate these two formats of state and how the system would react if you originally provided a state configuration of format #2, please use the [WebSocket debugger](https://ove.readthedocs.io/en/latest/docs/APP_DEVELOPMENT.html#debugging-communication-via-websockets).

**Comment by senakafdo** [comment]
Since we are discussing differences of state models provided to controller and viewers, there is also another difference concerning the images, maps and also networks and webrtc apps. All of these apps accept a "URL" as an alternative to providing a app-specific state configuration. This too would only be interpreted by the controller. When you have provided a URL, the controller will parse that state configuration and subsequently convert that into an app-specific state configuration and update the state. This is what would then be understood by the rest of the controller code and also the viewers.

A transformation like the above could only be done once and by a single app-instance, and hence the choice of the controller rather than using the viewers.

**Comment by jamesscottbrown** [comment]
A user should not have to calculate viewport details themselves: these are an implementation detail that should be abstracted away. However, reverse engineering each embedded library to determine how to do this calculation without needing to load specific content in the controller is potentially a waste of time.

The current implementation is not scalable: if I wanted to create 1000 image sections from my laptop, I would need to open 1000 tabs in my browser, which would obviously be a disaster.

One alternative would be for OVE Core to handle this by (optionally) automatically loading one controller per section.

 We could add a Boolean `waitForController` option to the state; if this is `false`, then when OVE Core creates a clientSection that includes the top-left corner of a section (i.e. `window.ove.geometry.x === window.ove.geoemtry.y === 0`), it could also load the corresponding controller into an invisible `iframe`, wait for the expanded state to be broadcast, and then delete this iframe.

This would increase the scalability and usability of many apps without wouldn't needing to modify the current controller/viewer design.

**Comment by senakafdo** [comment]
The API route should always be designed to be generic as possible and it would be incorrect for it to do any reverse engineering or interpretation of content etc. However, a utility (such as a UI to load content) can provide a generic approach where it asks users a set of questions and creates an image as a result.

However, this will not help someone who wants to create 1000 image sections. They would have to be using the APIs. 

What they can do is to use a tool, observe the payload, modify it to be a template, and then inject into it the dimensions of their specific image or configuration attributes related to the specific version of the library in use. The approach cannot be automated or documented, as it will vary based on the kind of image the user would be uploading.

Below is one such template:

```json
"load": {
  "config": {
    "panHorizontal": false,
    "panVertical": false,
    "wrapHorizontal": true,
    "wrapVertical": true,
    "visibilityRatio": 1,
    "id": "contentDiv",
    "prefixUrl": "/images/",
    "animationTime": 0,
    "tileSources": "http://obj-store/bucket/IMAGE_NAME.dzi"
  },
  "viewport": {
    "bounds": {
      "x": 0,
      "y": 0,
      "w": 1,
      "h": "IMAGE_HEIGHT/IMAGE_WIDTH"
    },
    "zoom": 1
  }
}
```

> One alternative would be for OVE Core to handle this by (optionally) automatically loading one controller per section.
>
> We could add a Boolean `waitForController` option to the state; if this is `false`, then when OVE Core creates a clientSection that includes the top-left corner of a section (i.e. `window.ove.geometry.x === window.ove.geoemtry.y === 0`), it could also load the corresponding controller into an invisible `iframe`, wait for the expanded state to be broadcast, and then delete this iframe.

I am strongly against these kinds of use-case specific hacks. We cannot load a controller inside a viewer just to make an end-user's life easy.

**Comment by jamesscottbrown** [comment]
After some discussion, @senakafdo  suggested writing separate `converter` microservices to convert the state from 'concise' human-readable forms to the expanded state format required by the apps. 

A separate ` loader` microservice would take care of both calling the converter service, and actually creating a section with the converted state.

**Comment by senakafdo** [comment]
The fix for the Preview UI now makes it possible to download a project.json which will have the proper formats for all assets including images. It therefore makes it possible for someone to provide a URL, preview its layout and download the corresponding project.json structure, and avoid having to load the controller in subsequent attempts.

**Comment by jamesscottbrown** [comment]
This is a useful feature in the Preview UI, but as this only reduces the number of times that the controller must be loaded to 1 (rather than 0) it does not resolve the underlying issue.
