### ISSUE TITLE
[Charts App] Chart does not scale to fit section dimensions

### ISSUE THREAD

**Issue by senakafdo** [ove/ove-apps#117]
It seems that the vegaArea division is rescaled but the canvas within it is still having the original dimensions, which seems to be the cause of this issue.

**Comment by jamesscottbrown** [comment]
I think the app is working correctly: the size of the chart is determined by the `width` and `height` options, which may be smaller than the size of the section in which the chart is being drawn.

**Comment by senakafdo** [comment]
@jamesscottbrown, ok, so other apps follow a model where the user needs not explicitly provide the dimensions of the content and they are automatically set to suit the dimensions of the target section. In a couple of apps the controller computes it, but for most apps it is automatically computed by the viewers. Can we therefore make the specification of `width` and `height` optional and get the viewers to set them to match the dimensions of the section (while preserving the aspect ratio and centering the chart)? Based on what you've noted, this would be a simple equation that can be computed irrespective of what the graph was displaying.

**Comment by jamesscottbrown** [comment]
This was fixed by https://github.com/ove/ove-apps/pull/162
