### ISSUE TITLE
Reducing size of browser displaying controller causes section of view to disappear

### ISSUE THREAD

**Issue by jamesscottbrown** [ove/ove-apps#123]
If the controller of the images app is opened in a web browser, and the size of browser window is subsequently reduced, then a portion of the middle of the image will disappear from the corresponding viewers.

**Comment by senakafdo** [comment]
@jamesscottbrown, the fixes seems to be in the source. Would you be able to validate what is potentially going wrong here?

**Comment by jamesscottbrown** [comment]
I tried to reproduce the error today and was unable to. I'm not sure why this occured when testing the performance of image tiles served directly from minio.
