### ISSUE TITLE
Name of Whiteboard App

### ISSUE THREAD

**Issue by jamesscottbrown** [ove/ove-apps#133]
I think that 'Whiteboard' is a misleading name for this app.

A physical whiteboard is opaque: you can't see through a whiteboard to see what is behind it at the same time as whatever has been drawn on it. A more fitting comparison is to a sheet of acetate transparency.

What the app provides is the ability to *draw freehand annotations*.

**Comment by senakafdo** [comment]
[Whiteboard in computing](https://en.oxforddictionaries.com/definition/whiteboard) is a bit different to whiteboard in its physical sense. I'm happy to change the name of the app to something more suitable, but if Whiteboard is what best describes what it does, then we can stick to it.

In terms of functionality the app does allow you to draw freehand as well as input text, which may or may not be annotations.

**Comment by senakafdo** [comment]
Resolving as we cannot think of a better name for this app for a month or so. Lets reopen this issue after have a F2F chat with possible names and if it makes sense to change the name of this app along those lines.
