### ISSUE TITLE
Audio app does not meet release standards

### ISSUE THREAD

**Issue by senakafdo** [ove/ove-apps#16]
Please test/fix functionality and also the issues reported by codacy.

**Comment by oserban** [comment]
I fixed most of the linting errors on the branch, but there are still a few more:
- the app may be incomplete as the OVEHowler class is not used anywhere
- the same file has missing imports and a commented require
- the linter does not like the swagger config, but this may be an issue with the linter config

**Comment by senakafdo** [comment]
@oserban, yes. Linting issues can be tested and fixed by running ESLint either using an IDE (such as Visual Studio Code), on the command line, or by integrating it with the lerna build.

More than the codacy issues, we have not yet tested this fully within a dev environment. It is most likely that an app may have issues that are only spotted during integration testing. I fixed one bug in the SVG app after the PR was merged, for instance. The implementation worked for many examples but failed for a few and it was only spotted after a comprehensive visualisation was written and it being throughly tested as a result.

**Comment by davidbirchwork** [comment]
The Issue-16 branch brings this app up to release standards. 
This app is now fully tested in the DEV environment. 
All methods are tested and functional 
ESLint run and issues fixed. 

The current positional audio implementation is functional but applies the same panning to each screen. 
Support for true positionality will await additional features in OVE core see https://github.com/ove/ove/issues/25 

Please may this issue be closed, a new issue relating directly to the positional audio aspects may opened if required.

**Comment by senakafdo** [comment]
@davidbirchwork, I have added some comments to #24 - happy to resolve once those issues are plus any other review comments are addressed.

**Comment by davidbirchwork** [comment]
This is resolved with PR #24 merged
