### ISSUE TITLE
[HTML App]: updated state not propogated until controller reloaded

### ISSUE THREAD

**Issue by jamesscottbrown** [ove/ove-apps#175]
If I POST a new state to `HTML_APP_HOST/instances/<section_id>/state`, then this update is not broadcasted to the viewers until I either refresh or resize (!) the controller app.

Similar problems may occur in other apps.

**Comment by senakafdo** [comment]
A chage of state via the API will change nothing in an app, unless you broadcast the change to the app. However, you can redeploy/update the app with a new state which will be reflected immediately.

**Comment by jamesscottbrown** [comment]
We spoke about this and you said that you would add a clarifying note to the API docs to tell people that the route exposed by each app at `/instances/{id}/state` was intended for internal use, and that if they wanted to update an app they should post to `/sections/{id}` of OVE Core instead.
