### ISSUE TITLE
[Videos App] Why is the background grey?

### ISSUE THREAD

**Issue by jamesscottbrown** [ove/ove-apps#182]
The videos app has a grey (`#222`) background, set by [this line](https://github.com/ove/ove-apps/blob/54eed1ed69a7692eab65cca56a16da398becc61a/packages/ove-app-videos/src/client/common/videos.css#L12) in `videos.css`.

This has the consequence that if a video section is used to load a video with a different aspect ratio, the region that does not contain the video is visible as grey rectangles, rather than being invisible (as it would be if `background: none;` was used instead).

**Comment by senakafdo** [comment]
There is no special reason but the video players do not always have a transparent background and whatever set at the page level won't make a difference. Also, is it not possible to resize the video section to suit the dimensions of the video?

**Comment by senakafdo** [comment]
@jamesscottbrown, I don't see a good reason to fix this issue as the app does not support crop, zoom or pan. Therefore, anyone not interested in the grey background can choose section dimensions that suit the video dimensions. A separate complication of fixing this issue (as proposed) is that the occlusion culling functionality supported by this app will get unwantedly complicated as we also need to compute the boundaries of what is being culled, which is a bit challenging with streaming video etc which may only be available after some point in time. I'm therefore resolving this issue as Won't Fix.
