### ISSUE TITLE
[Audio app] Complete implementation of setPosition

### ISSUE THREAD

**Issue by senakafdo** [ove/ove-apps#33]

**Comment by davidbirchwork** [comment]
Note that this is now possible via https://github.com/ove/ove/commit/2f5d382a8243be303b076b6e49b765abdb781965
I will schedule this work for next week as i have other commitments this week. 

I do not believe this is a blocker because the app is certainly functional.

**Comment by senakafdo** [comment]
@davidbirchwork it clearly says [implementation pending **blocker**](https://github.com/ove/ove-apps/tree/master/packages/ove-app-audio) in the documentation.

**Comment by davidbirchwork** [comment]
@senakafdo yes the implementation of this feature was blocked. It is now unblocked, you may remove that reference in the documentation. 

That is quite separate to whether this issue is blocking something else. The app itself is quite functional and this feature is blocking nothing else.

**Comment by senakafdo** [comment]
@davidbirchwork, did you implement anything further to make setPosition work in the audio app following the resolution of that issue? If not, let's fix it first - which is the intention of this issue.

My following of the documentation you wrote, was that there was a critical limitation in the application's functionality. If that was never the case, I'm also wondering why you added that line in the first place.
