### ISSUE TITLE
Unable to publish 0.2.0 Production Release to Docker Hub

### ISSUE THREAD

**Issue by senakafdo** [ove/ove-apps#45]
Step 6/9 : RUN npm run install:prod
 ---> Running in 547442cb8e40

> ove@ install:prod /usr/src/app
> lerna bootstrap --hoist -- --production --no-optional

lerna notice cli v3.4.3
lerna info Bootstrapping 9 packages
lerna info Installing external dependencies
lerna info hoist Installing hoisted dependencies into root
lerna info hoist Pruning hoisted dependencies
lerna info hoist Finished pruning hoisted dependencies
lerna ERR! npm install --production --no-optional exited 1 in 'ove'
lerna ERR! npm install --production --no-optional stderr:
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/assert-plus-27d8fb6e/package.json'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/send-f41170a3/package.json'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/assert-plus-27d8fb6e/README.md'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/send-f41170a3/HISTORY.md'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/assert-plus-27d8fb6e/assert.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/send-f41170a3/index.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/assert-plus-27d8fb6e/AUTHORS'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/assert-plus-27d8fb6e/CHANGES.md'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-scenegraph-1735237c/src/util/canvas/clip.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-scenegraph-1735237c/src/util/canvas/color.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-scenegraph-1735237c/src/util/canvas/draw.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-scenegraph-1735237c/src/util/canvas/fill.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-scenegraph-1735237c/src/util/canvas/gradient.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/JSONStream-f7734e2d/test/fixtures/couch_sample.json'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-scenegraph-1735237c/src/util/canvas/image.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/JSONStream-f7734e2d/test/fixtures/depth.json'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-scenegraph-1735237c/src/util/canvas/pick.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/underscore-contrib-8464bd98/test/vendor/jslitmus.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/JSONStream-f7734e2d/test/fixtures/error.json'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-scenegraph-1735237c/src/util/canvas/resize.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/JSONStream-f7734e2d/test/fixtures/header_footer.json'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-scenegraph-1735237c/src/util/canvas/stroke.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/underscore-contrib-8464bd98/test/vendor/qunit.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/JSONStream-f7734e2d/test/fn.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/JSONStream-f7734e2d/test/gen.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-60346f2c/src/parsers/guides/axis-config.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/JSONStream-f7734e2d/test/header_footer.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-60346f2c/src/parsers/guides/axis-domain.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/JSONStream-f7734e2d/test/issues.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-60346f2c/src/parsers/guides/axis-grid.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/JSONStream-f7734e2d/test/keys.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-164e4e26/src/parsers/encode/adjust-spatial.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-60346f2c/src/parsers/guides/axis-labels.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/JSONStream-f7734e2d/test/map.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-164e4e26/src/parsers/encode/color.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-60346f2c/src/parsers/guides/axis-ticks.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/JSONStream-f7734e2d/test/multiple_objects_error.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-164e4e26/src/parsers/encode/encode-util.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-60346f2c/src/parsers/guides/axis-title.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/JSONStream-f7734e2d/test/multiple_objects.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-164e4e26/src/parsers/encode/entry.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-60346f2c/src/parsers/guides/constants.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/JSONStream-f7734e2d/test/null.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-164e4e26/src/parsers/encode/expression.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-60346f2c/src/parsers/guides/guide-group.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/JSONStream-f7734e2d/test/parsejson.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-164e4e26/src/parsers/encode/field.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-60346f2c/src/parsers/guides/guide-mark.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/JSONStream-f7734e2d/test/run.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-164e4e26/src/parsers/encode/gradient.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-60346f2c/src/parsers/guides/guide-util.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/JSONStream-f7734e2d/test/stringify_object.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-164e4e26/src/parsers/encode/property.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-60346f2c/src/parsers/guides/legend-gradient-discrete.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/JSONStream-f7734e2d/test/stringify.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-164e4e26/src/parsers/encode/rule.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-60346f2c/src/parsers/guides/legend-gradient-labels.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/JSONStream-f7734e2d/test/test.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-164e4e26/src/parsers/encode/scale.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-60346f2c/src/parsers/guides/legend-gradient.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/JSONStream-f7734e2d/test/test2.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-164e4e26/src/parsers/encode/set.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-60346f2c/src/parsers/guides/legend-symbol-groups.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/JSONStream-f7734e2d/test/two-ways.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-164e4e26/src/parsers/expression/arrays.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-60346f2c/src/parsers/guides/legend-title.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-164e4e26/src/parsers/expression/ast.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-60346f2c/src/parsers/marks/clip.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-164e4e26/src/parsers/expression/codegen.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-5f3ac4e8/build/vega.min.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-60346f2c/src/parsers/marks/data.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-60346f2c/src/parsers/marks/definition.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-164e4e26/src/parsers/expression/data.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-60346f2c/src/parsers/marks/facet.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-164e4e26/src/parsers/expression/encode.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-60346f2c/src/parsers/marks/interactive.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-164e4e26/src/parsers/expression/flush.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-60346f2c/src/parsers/marks/marktypes.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-164e4e26/src/parsers/expression/format.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-60346f2c/src/parsers/marks/role.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-164e4e26/src/parsers/expression/geo.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-60346f2c/src/parsers/marks/roles.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-164e4e26/src/parsers/expression/inscope.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-60346f2c/src/parsers/marks/subflow.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-164e4e26/src/parsers/expression/log.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-164e4e26/src/parsers/expression/merge.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-164e4e26/src/parsers/expression/modify.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-164e4e26/src/parsers/expression/pinch.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-164e4e26/src/parsers/expression/prefixes.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-164e4e26/src/parsers/expression/quarter.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-164e4e26/src/parsers/expression/scale-gradient.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-164e4e26/src/parsers/expression/scale.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-parser-164e4e26/src/parsers/expression/selection.deprecated.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/vega-lib-d6f7f338/build/vega.min.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/swagger-ui-dist-78c4e7d9/swagger-ui-bundle.js.map'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/openseadragon-97d10bf1/build/openseadragon/openseadragon.min.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/openlayers-832e3b4f/coverage/index.html'
npm ERR! code E404
npm ERR! 404 Not Found: har-validator@5.1.2

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-22T00_10_01_924Z-debug.log

lerna ERR! npm install --production --no-optional exited 1 in 'ove'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ove@ install:prod: `lerna bootstrap --hoist -- --production --no-optional`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ove@ install:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-22T00_10_02_271Z-debug.log
ERROR: Service 'ove-apps' failed to build: The command '/bin/sh -c npm run install:prod' returned a non-zero code: 1

**Comment by oserban** [comment]
It builds properly without any error on my machine

**Comment by jamesscottbrown** [comment]
I think it may be a mac-specific issue: see [this issue](https://github.com/docker/for-mac/issues/2296) for example

**Comment by oserban** [comment]
The package-lock.json is OS specific, so the solution was to add the file to the .dockerignore list. Lerna and npm recreates the file on the install command.
