### ISSUE TITLE
Setting image tile source as described in README does not work

### ISSUE THREAD

**Issue by jamesscottbrown** [ove/ove-apps#46]
Specifying a tile source when creating an image section through the API as specified in the README doesn't work: the default `highsmith` image is always displayed.

 [The example in the README](https://github.com/ove/ove-apps/tree/master/packages/ove-app-images) is:

```bash
curl --header "Content-Type: application/json" --request POST --data '{"app": {"url": "http://OVE_APP_IMAGES_HOST:PORT","states": {"load": {"tileSources": "https://openseadragon.github.io/example-images/highsmith/highsmith.dzi"}}}, "space": "OVE_SPACE", "h": 500, "w": 500, "y": 0, "x": 0}' http://OVE_CORE_HOST:PORT/section
```

I therefore tried the command:

```bash
curl --header "Content-Type: application/json" --request POST --data '{"app": {"url": "http://gdo-apps.dsi.ic.ac.uk:9082","states": {"load": {"tileSources": "https://openseadragon.github.io/example-images/pnp/pan/6a32000/6a32400/6a32487.dzi" }}}, "space": "DOCluster", "h": 4320, "w": 30720, "y": 0, "x": 0}' http://gdo-apps.dsi.ic.ac.uk:9080/section
```

But the Chrome console reports:

    [TRACE] 11/23/2018, 11:55:56.688  AM - OVE              : Sending message: {"appId":"images","sectionId":"10","message":{"config":{"tileSources":"https://openseadragon.github.io/example-images/highsmith/highsmith.dzi"},"viewport":{"bounds":{"x":-0.4268439581152169,"y":-0.07291172470506369,"w":1.8536879162304338,"h":1.4582344941012746},"zoom":0.5394651339334129}}}

It therefore tried to load the default image `highsmith.dzi`, rather than the image `6a32487.dzi` that I requested.

**Comment by senakafdo** [comment]
Fixed in #49.
