### ISSUE TITLE
Image App Save State of Zoom and Pan

### ISSUE THREAD

**Issue by davidbirchwork** [ove/ove-apps#47]
Following the model from the Graph App which stores the queries applied. 
I wonder if it makes sense for the images app to record its current pan and zoom level so that it can be restored - what does @ove/ove think?

**Comment by senakafdo** [comment]
@davidbirchwork zoom and pan can be configured via the tileSources property using OSD configuration, as documented on the README of this app. Please try using the app according to the README and tell us if something within OSD doesn't work as documented and we can help you with it. This is **not a bug** and therefore I am closing this issue.

**Comment by davidbirchwork** [comment]
The requested feature is now implemented in https://github.com/ove/ove-apps/pull/49/files 

many thanks
