### ISSUE TITLE
Code review for PDF app

### ISSUE THREAD

**Issue by jamesscottbrown** [ove/ove-apps#70]
Since several changes recently went straight to master without review, I thought I'd read through and give some comments on them.

## General

There are lots of instances of things like 

```
<so something thing>
<log result>
<do other thing>
```

that I think would be slightly clearer as

```
<so something thing>
<log result>

<do other thing>
```

[For example](https://github.com/ove/ove-apps/blob/master/packages/ove-app-pdf/src/client/common/pdf.js#L60),

```JavaScript
        // The scale can be cached in the current state or provided as a configuration setting.
        // If this not provided the default value will be used.
        const scale = state.scale || state.settings.scale || Constants.DEFAULT_SCALE;
        log.trace('Using scale:', scale);
        let viewport = firstPage.getViewport(scale);

```

would be

```JavaScript
        // The scale can be cached in the current state or provided as a configuration setting.
        // If this not provided the default value will be used.
        const scale = state.scale || state.settings.scale || Constants.DEFAULT_SCALE;
        log.trace('Using scale:', scale);

        let viewport = firstPage.getViewport(scale);

```

This is a minor point.

## package.json

1. D3 [became modular in version 4.0](https://github.com/d3/d3/blob/master/CHANGES.md#changes-in-d3-40) (which resulted in lots of minor breaking changes).

I don't think you need to depend on all of d3 for the zooming/panning to work - I think that [d3-zoom](https://www.npmjs.com/package/d3-zoom) and [d3-selection](https://www.npmjs.com/package/d3-selection) should be sufficient.

### Evaluate function

1. It is difficult to read the [evaluate function](https://github.com/ove/ove-apps/blob/c21d01a146fec3330572ffc61156804848cd47bb/packages/ove-app-pdf/src/index.js#L27):

```JavaScript

        const evaluate = function (input, obj) {
            return obj ? ((input.indexOf('.') === -1) ? obj[input]
                : evaluate(input.substring(input.indexOf('.') + 1), obj[input.substring(0, input.indexOf('.'))]))
                : undefined;
        };

```

I think it would be much clearer as something like:

```JavaScript

        const evaluate = function (input, obj) {
        	const splitPoint = input.indexOf('.');
        	const stringStart = input.substring(0, splitPoint);
        	const stringEnd = input.substring(splitPoint + 1);

            return obj ? ((splitPoint === -1) ? obj[input]
                : evaluate(stringEnd, obj[stringStart]))
                : undefined;
        };

```

Also, this function is defined twice in this file, and also in the maps, images, and networks apps. I think it would make sense to extract it out as a util method.

2 . I think that the structure of the `result` object is slightly clearer if

```JavaScript
    const result = {
        zoom: target.scale / source.scale,
        pan: { x: source.offset.x - target.offset.x, y: source.offset.y - target.offset.y }
};
```

is written as 

```JavaScript
    const result = {
        zoom: target.scale / source.scale,
        pan: {
            x: source.offset.x - target.offset.x,
            y: source.offset.y - target.offset.y
        }
    };
```

as this makes the equivalence between x and y more apparent.

## client/common/pdf.js

1. In [`client/common/pdf.js`](https://github.com/ove/ove-apps/blob/master/packages/ove-app-pdf/src/client/common/pdf.js#L130), the jQuery selector `$('#page' + i)` is repeated; it could be used once and stored in a variable.

2. When [scaling the page](https://github.com/ove/ove-apps/blob/master/packages/ove-app-pdf/src/client/common/pdf.js#L82) it would be helpful to have comments "Scale to fit width" and "Scale to fit height"

3. It is difficult to read the margin calculations:

```JavaScript

            const marginX = (state.offset.x || 0) + dim.border.x + pageDim.border.x + (dim.w + pageGap) *
                (scrollDir === Constants.Scrolling.VERTICAL ? (i - firstPage.pageNumber) % dim.c : Math.floor((i - firstPage.pageNumber) / dim.r));
            const marginY = (state.offset.y || 0) + dim.border.y + pageDim.border.y + (dim.h + pageGap) *
                (scrollDir !== Constants.Scrolling.VERTICAL ? (i - firstPage.pageNumber) % dim.r : Math.floor((i - firstPage.pageNumber) / dim.c));

```
 I suggest refactoring to something like:

```JavaScript

			let pageRow = 0, pageColumn = 0;
			if (Constants.Scrolling.VERTICAL){
				pageColumn = (i - firstPage.pageNumber) % dim.c;
				pageRow    = (i - firstPage.pageNumber) % dim.r;
			} else {
				pageColumn = Math.floor((i - firstPage.pageNumber) / dim.r);
				pageRow    = Math.floor((i - firstPage.pageNumber) / dim.c);
			}

            const marginX = (state.offset.x || 0) + dim.border.x + pageDim.border.x + (dim.w + pageGap) * pageColumn;
            const marginY = (state.offset.y || 0) + dim.border.y + pageDim.border.y + (dim.h + pageGap) * pageRow;

```

## client/control/pdf.js

1. Rather [than commenting](https://github.com/ove/ove-apps/blob/master/packages/ove-app-pdf/src/client/control/pdf.js#L39) that "Zoom is limited to a factor of 10", why not replace 10 with a constant ``MAX_ZOOM_LEVEL``?

2. I think that 

```JavaScript
getScalingFactor = function () {
    return Math.max(window.ove.geometry.section.w / Math.min(document.documentElement.clientWidth, window.innerWidth),
        window.ove.geometry.section.h / Math.min(document.documentElement.clientHeight, window.innerHeight));
};

```

would be clearer as

```JavaScript
getScalingFactor = function () {
	const horizontalScaleFactor = window.ove.geometry.section.w / Math.min(document.documentElement.clientWidth, window.innerWidth);
	const verticalScaleFactor   = window.ove.geometry.section.h / Math.min(document.documentElement.clientHeight, window.innerHeight);

    return Math.max(horizontalScaleFactor, verticalScaleFactor);
};

```

**Comment by senakafdo** [comment]
@jamesscottbrown, I like these comments, but it would be easier if you could also provide code examples that actually work. Right now, it is very confusing, as I have to read back and forth to understand what currently works, what you are trying to say and and then a final version that meets most of what you say and will also work at the same time, :).

**Comment by senakafdo** [comment]
Fixed all apart from D3. What you suggest will work for some modules like [d3-selection](https://www.npmjs.com/package/d3-selection). But, [d3-zoom](https://www.npmjs.com/package/d3-zoom) needs 8 other dependencies, and it becomes really hard to manage these as they keep evolving with new versions etc. There is really no harm in using the d3.min.js which is some 232K in size.
