### ISSUE TITLE
Code review for replicator app

### ISSUE THREAD

**Issue by jamesscottbrown** [ove/ove-apps#74]
## src/client/view/replicator.js

1. I think [the condition](https://github.com/ove/ove-apps/blob/master/packages/ove-app-replicator/src/client/view/replicator.js#L131) `bounds.w * maxHeight >= maxWidth * bounds.h` would be clearer if it were written as ` maxWidth / bounds.w  <=  maxHeight / bounds.h`. The two expressions in the inequality are then the same as the two expressions that could be assigned to `scale`.

2. This [viewport calculation](https://github.com/ove/ove-apps/blob/master/packages/ove-app-replicator/src/client/view/replicator.js#L155) is unreadable:

```JavaScript

    let viewport = {
        x: g.x - offset.x - config.margin / 2 <= 0 ? bounds.x : bounds.x + (g.x - offset.x - config.margin / 2) / scale,
        y: g.y - offset.y - config.margin / 2 <= 0 ? bounds.y : bounds.y + (g.y - offset.y - config.margin / 2) / scale,
        w: g.x + g.w - offset.x - config.margin / 2 <= 0 ? 0 : g.x - offset.x - config.margin / 2 > g.w ? g.w / scale : (g.w - g.x + offset.x + config.margin / 2) / scale,
        h: g.y + g.h - offset.y - config.margin / 2 <= 0 ? 0 : g.y - offset.y - config.margin / 2 > g.h ? g.h / scale : (g.h - g.y + offset.y + config.margin / 2) / scale
    };

```

I suggest re-writing as something like:

```JavaScript

   let viewport = {};

    const a = g.x - offset.x - config.margin / 2;
    const b = g.y - offset.y - config.margin / 2;

    viewport.x = bounds.x + Math.max(0, a) / scale;
    viewport.y = bounds.y + Math.max(0, b) / scale;

    if ( a + g.w <= 0 ){
    	viewport.w = 0;
    } else if (a > g.w) {
        viewport.w = g.w / scale;
    } else {
        viewport.w = (g.w - a) / scale;
    }

    
    if (b + g.h <= 0) {
        viewport.h = 0;
    } else if (b > g.h) {
        viewport.h =  g.h / scale;
    } else {
        viewport.h = (g.h - b) / scale;
    }


```

**Comment by senakafdo** [comment]
> I think the condition bounds.w * maxHeight >= maxWidth * bounds.h would be clearer if it were written as maxWidth / bounds.w <= maxHeight / bounds.h. The two expressions in the inequality are then the same as the two expressions that could be assigned to scale

I have tested the outcome of previous and opted to use the current due to loss of precision.
