### ISSUE TITLE
[Videos app] Control of audio

### ISSUE THREAD

**Issue by jamesscottbrown** [ove/ove-apps#77]
The Video app currently provides no control over sound, which seems like a major omission.

Like the audio app, the videos app should provide a way to `mute`/`unmute` and increase or decrease the volume.

We probably want to keep all clients displaying the same section muted except for one, and to have some way to specify which.

**Comment by senakafdo** [comment]
I don't think this is required or the end result of this would mean we do not need to have the audio app. It is much more complicated than muting the audio on one and playing it many in a LHRD-environment which would generally have multi-channel audio. This is why there exists an audio app that is capable of playing such sort of audio. Optionally, the video app can have such sort of audio playback capability and we can simply omit the audio app altogether, which might also make sense if we are to synchronise audio and video playback to start/stop at the same time.

**Comment by senakafdo** [comment]
> The audio currently supports only `webm`, `mp3` and `wav`, so there's currently no way to just play a video with sound, and this is a significant limitation in a video player.
> 
> Support for fancy multichannel audio would be nice, but I don't think it is absolutely necessary.

I agree on both points. The only issue is that we would eventually end-up with two similar but very different things that will never fully interoperate. I'm not saying this is the case with what you propose here, but I'm looking at how this would evolve, if we make this decision, today. 

At the same time, the video app could also support audio playback, with an audio-only player. I will validate the viability of this option and we can decide. That way we probably won't have a confusion/duplication.
